### ISSUE TITLE
Черепашки и фрактал :)

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#10]
06c04557119b8deec2f5b9eb41d8c5232961b388 
antosha417

**Comment by StGalya** [comment]
@antosha417

**Comment by antosha417** [comment]
Фрактал нужно рисовать с использованием рекурсии. Ещё раз рассказывал это Мише Клюкину на прошлом семинаре, написал ему код. Пусть объяснит тебе.

Пока ставлю тебе 0,6 за задачу, чтобы поднять поправь код.
