### ISSUE TITLE
Анимация

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#3]
b7c10cc5194e81445e48ef79c41dca403797a894@antosha417

**Comment by StGalya** [comment]
@antosha417

**Comment by antosha417** [comment]
Нет смысла сдавать анимацию пока не сдашь графику, там одинаковые ошибки

**Comment by StGalya** [comment]
4abc595509a68493fb6111bd8ee48bf71c646205
@antosha417

**Comment by antosha417** [comment]
* Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
* Перепиши движение облака через циклы.
Пока ставлю тебе 0,8  за задачу, чтобы поднять поправь код.
