### ISSUE TITLE
Мячики и стенки

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#4]
415a55a0b8265fc4e68749f843e867f906100e29@antosha417

**Comment by StGalya** [comment]
@antosha417

**Comment by antosha417** [comment]
Удали импорты библиотек которые не используешь.
Много вывода в консоль, мне кажется это лишнее, лучше убрать 
Убери копипасту из функции `tick_handler`

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Пока ставлю тебе 0.65 за задачу, чтобы поднять исправь то, что я написал.

**Comment by StGalya** [comment]
ea525d682a2af5f27fe27d241d10e99dd672b8a7 @antosha417 
исправила. Но все равно не понимаю, как убирать копипасту. Это же условия написаны... я никуда их деть не могу

**Comment by antosha417** [comment]
Плохое сообщение к коммиту! Нужно писать что было сделано. Например: Убрала ненужные импорты и вывод в консоль

**Comment by antosha417** [comment]
Для x и для y у тебя одинаковые условия, сделай функцию

**Comment by StGalya** [comment]
38b8893b0d0ddec88603053dc4e30495d4b0013f
@antosha417

**Comment by antosha417** [comment]
При запуске программы получаю ошибки
![latest-screenshot](https://user-images.githubusercontent.com/14187674/49994650-17da5b00-ff9b-11e8-8416-e5dfb6a69c97.png)

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Пока ставлю тебе 0,7 за задачу, чтобы поднять поправь код.
