### ISSUE TITLE
Моя картинка (графика)

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#5]
03eb7d94039c50aac583d37e539b9848240a08da@antosha417

**Comment by StGalya** [comment]
@antosha417

**Comment by antosha417** [comment]
Давай хорошо подумаем над названиями переменных.

**Comment by antosha417** [comment]
По названию переменной мне должно быть понятно что ты в неё положила

**Comment by antosha417** [comment]
Очень много копипасты (одинаковых строк ) в программе, подумай как это можно циклами сделать

**Comment by antosha417** [comment]
Пока ставлю тебе 0,5  за задачу, чтобы поднять поправь код.

**Comment by StGalya** [comment]
4abc595509a68493fb6111bd8ee48bf71c646205
исправила прогу
@antosha417

**Comment by antosha417** [comment]
Вынеси создания окна, рисование, и закрывания окна в функцию и закрывай issue
