### ISSUE TITLE
Поймай шарик

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#6]
0ae4b763c101fda058eb2cf54d1e9a29e4c713a9@antosha417

**Comment by StGalya** [comment]
@antosha417

**Comment by antosha417** [comment]
Убери ненужные библиотеки

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Сделай так, чтобы я мог заработать только одно очко если я захочу много раз кликнуть на шарик

**Comment by antosha417** [comment]
Пока ставлю тебе 0.6  за задачу, чтобы поднять поправь код.

**Comment by StGalya** [comment]
я все исправляла по PEP 8

**Comment by antosha417** [comment]
Молодец, нужно до конца исправить. И поправить остальное, о чём я писал выше.
![latest-screenshot](https://user-images.githubusercontent.com/14187674/48921063-31ade400-eeae-11e8-8511-9566a92ab2c9.png)

**Comment by StGalya** [comment]
81866b55e2b4d5993f17b5f213d1c012bd58f1df @antosha417 
у меня больше ничего не подчеркивается. все исправила

**Comment by antosha417** [comment]
Плохое имя переменной xx, что в ней храниться? Мне кажется там может лежать координата x возведённая в квадрат или ещё что-то. 

Ты не поправила pep8 и не убрала ненужные библиотеки. Подойди ко мне на семинаре, я покажу как это делать.

> Сделай так, чтобы я мог заработать только одно очко если я захочу много раз кликнуть на шарик
этого тоже нет.

**Comment by StGalya** [comment]
c8c6e214915f36c631713270199a4c8a7456fa2c
@antosha417

**Comment by StGalya** [comment]
4e238adc467c1e6d3f4917182560a8e4a8a1b33b
@antosha417

**Comment by StGalya** [comment]
fea3264c7c219f6ecb38d79a1e1220ec926af795
@antosha417

**Comment by antosha417** [comment]
Не нужно каждый час в  issue присылать коммиты свои. Нужно сюда писать когда ты поправила код и готова его сдавать.

**Comment by antosha417** [comment]
Ты не поправила то, что я просил, не пиши, пожалуйста в issue пока не поправишь. Если есть какие-то вопросы, то обязательно задавай их в чате в телеграмме.

Тебе нужно:
* убрать ненужные библиотеки
* поправить pep8
* cделать так, чтобы игрок мог заработать только одно очко с одного шарика, даже если будет много раз на него кликать.

**Comment by StGalya** [comment]
5209d7f3c66eac82a1146edb7e18428fa828a5a0
@antosha417

**Comment by antosha417** [comment]
В коммите по ссылке выше ты просто удалила 2 пустые строки
![latest-screenshot](https://user-images.githubusercontent.com/14187674/49369884-90235f80-f703-11e8-9bc2-e31644e63716.png)

Не понимаю что проверять.

**Comment by antosha417** [comment]
Где ты используешь  модуль `time`  ?

**Comment by StGalya** [comment]
838c5ffe0489b06592b90200c837c3b4101be11b
@antosha417 
все исправила. больше нет лишних библиотек, пайчарм не ругается на ошибки, нельзя сделать больше одного клика.

**Comment by antosha417** [comment]
Закрывай issue
