### ISSUE TITLE
Пушка

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#7]
aa40e87530eef81efcd81b2767c05abbc1ba3b50@antosha417
Отправляла вовремя. Просто не сделала Issues.

**Comment by StGalya** [comment]
@antosha417

**Comment by antosha417** [comment]
К сожалению всё равно во второй дедлайн не уложилась(

**Comment by StGalya** [comment]
почему не уложилась? я же сбросила программу намного раньше, чем в 11 вечера. просто назвала по другому. другой ишьюс, не этот

**Comment by antosha417** [comment]
Давай в этом останемся, чтобы видеть прогресс?

**Comment by StGalya** [comment]
хорошо, но я ту программу буду дорабатывать скорее всего. Так получается, я ведь уложилась в дедлайн :)

**Comment by antosha417** [comment]
Сюда её скинь, а тот issue закрой

**Comment by StGalya** [comment]
просто поменять текст программы этой на ту? или как ?

**Comment by antosha417** [comment]
прочитай пожалуйста правила игры, что тебе не понятно там? 
меняешь файлы -> коммитишь -> добавляешь коммиты в issue когда всё готово.

**Comment by StGalya** [comment]
окей) я просто думала, что можно еще один файл сюда добавить

**Comment by antosha417** [comment]
Можешь добавить

**Comment by antosha417** [comment]
aec0f1b

**Comment by antosha417** [comment]
Списывала?

**Comment by antosha417** [comment]
Пока ставлю тебе 0,4  за задачу, чтобы поднять поправь код.

**Comment by StGalya** [comment]
aec0f1bf5e8ec40a9a8fb81678f2fc9b36ea158f 
перекинула из другого ишьюса, чтобы было удобно
@antosha417

**Comment by antosha417** [comment]
Замечательно, я это уже написал выше. Ты что-нибудь поправила?

**Comment by StGalya** [comment]
в этой программе еще нет. так как делала задание про драконов. сейчас правлю остальные проги

**Comment by antosha417** [comment]
Пиши сюда, когда есть что проверять, хорошо? Если есть какие-то вопросы лучше задавать их в чат, там быстрее ответят.
