### ISSUE TITLE
Drakonchiki

### ISSUE THREAD

**Issue by StGalya** [StGalya/prog_Stupnikova#9]
@antosha417 7db3a0545821b257770039b21d5a675863e17c6f

**Comment by StGalya** [comment]
d85a6ce588850293e93ec2cb3402e4b8460fc067 новая версия @antosha417

**Comment by StGalya** [comment]
95eb22ae8ac8e6d129c4f8c227408ed54d3e0dfa
улучшенная версия @antosha417

**Comment by antosha417** [comment]
Я не понимаю что ты сделала. Пиши, пожалуйста хорошие сообщения к коммитам.
Я читаю: version 1.3 . Как это понимать? Что ты там улучшила?

**Comment by antosha417** [comment]
Напиши тогда сюда по пунктам что ты сделала.
Например так:
```
Было сделано: 
* добавлен класс героя 
* добавлен класс черного дракона, который раскладывает на простые множетели
* добавлен класс крокодила, который всегда кусает
* При некорректном вводе теперь даётся только одна дополнительная попытка
* ...
```

**Comment by antosha417** [comment]
Вообще это и должна быть история коммитов.
